table dates
	lineageTag: 418fa1e1-8f59-4a19-a5fb-a25122d9c99d

	column date_id
		dataType: int64
		formatString: 0
		lineageTag: 2c7f289b-5556-42a5-9949-d33b50a070e4
		summarizeBy: none
		sourceColumn: date_id

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3d6d7736-5cf0-4bd4-87d8-363e9a0d3099
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: f9564d23-45ed-4900-8206-680ffaba840c
			defaultHierarchy: LocalDateTable_5ce84caf-9008-42fd-917d-9a18cb396e71.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column date_month
		dataType: int64
		formatString: 0
		lineageTag: 1d9a5885-a821-425e-a56a-d804c9ebabd5
		summarizeBy: sum
		sourceColumn: date_month

		annotation SummarizationSetBy = Automatic

	column date_day
		dataType: int64
		formatString: 0
		lineageTag: 9c91acef-0e71-4001-8a8e-5fe4b6e1ce65
		summarizeBy: sum
		sourceColumn: date_day

		annotation SummarizationSetBy = Automatic

	column date_weekday
		dataType: string
		lineageTag: 2cc0effd-527a-4dc5-9f06-07bc4f24f1a9
		summarizeBy: none
		sourceColumn: date_weekday

		annotation SummarizationSetBy = Automatic

	column date_week
		dataType: int64
		formatString: 0
		lineageTag: 22d033f3-fcf1-4a08-b5f1-3532a847fdb7
		summarizeBy: sum
		sourceColumn: date_week

		annotation SummarizationSetBy = Automatic

	partition dates = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\test-projects\dataviz-project\dates.csv"),[Delimiter=",", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"date_id", Int64.Type}, {"date", type date}, {"date_month", Int64.Type}, {"date_day", Int64.Type}, {"date_weekday", type text}, {"date_week", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

