table products
	lineageTag: 49f947fb-3127-499c-9cd5-c0a201dcff6b

	column product_id
		dataType: int64
		formatString: 0
		lineageTag: 726c6b4f-9425-40ae-89e0-8ba6fbf0de3f
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column product_name
		dataType: string
		lineageTag: d6f93799-8bff-476b-96d4-e2b22cad7a4b
		summarizeBy: none
		sourceColumn: product_name

		annotation SummarizationSetBy = Automatic

	column product_category
		dataType: string
		lineageTag: e92e59da-3256-4c94-b55e-5ddd80cecbd8
		summarizeBy: none
		sourceColumn: product_category

		annotation SummarizationSetBy = Automatic

	column product_brand
		dataType: string
		lineageTag: 530bd946-2036-46fb-bd36-dd5771a9c0d9
		summarizeBy: none
		sourceColumn: product_brand

		annotation SummarizationSetBy = Automatic

	column product_model
		dataType: string
		lineageTag: 2d95a018-3d7a-41e9-9c47-2b401b661524
		summarizeBy: none
		sourceColumn: product_model

		annotation SummarizationSetBy = Automatic

	column product_list_price
		dataType: double
		lineageTag: a8b14024-f8b5-479c-9da3-8d04e39f73f7
		summarizeBy: none
		sourceColumn: product_list_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column product_standard_cost
		dataType: double
		lineageTag: e4891218-891f-46e4-8d4f-3bf731fd2a20
		summarizeBy: none
		sourceColumn: product_standard_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column product_is_active
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 81a69c2e-526f-4bd1-a732-1baf9ce2800a
		summarizeBy: none
		sourceColumn: product_is_active

		annotation SummarizationSetBy = Automatic

	partition products = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\test-projects\dataviz-project\products.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"product_id", Int64.Type}, {"product_name", type text}, {"product_category", type text}, {"product_brand", type text}, {"product_model", type text}, {"product_list_price", type number}, {"product_standard_cost", type number}, {"product_is_active", type logical}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

